[package]
name = "brand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.7", features = ["derive"] }
log = "0.4.21"
regex = "1.10.5"
serde = "1.0.203"
serde_json = "1.0.118"
sha256 = "1.5.0"
simple_logger = { version = "5.0.0", features = ["stderr"] }
winnow = "0.6.13"
